# Generated by Django 4.0.5 on 2022-07-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping_address',
            new_name='ShippingAddress',
        ),
    ]
